name: release

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build
        run: go build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test
        run: go test -v ./...

      - name: Staticcheck
        run: |
          go get -u honnef.co/go/tools/cmd/staticcheck
          staticcheck ./...
          
  publish:
    runs-on: ubuntu-latest
    needs: test
    steps: 
      - name: Package
        run: zip package.zip wheretogo
      - name: AWS CodeDeploy
        uses: sourcetoad/aws-codedeploy-action@v1
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          codedeploy_name: wheretogo
          codedeploy_group: prod
          archive: package.zip
          s3_bucket: codemonauts-codeship
          s3_folder: wheretogo
