name: release

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build
        run: CGO_ENABLED=0 go build

      - name: Upload compiled binary
        uses: actions/upload-artifact@v2
        with:
          name: binary
          path: wheretogo

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Test
        run: go test -v ./...

      - name: Staticcheck
        run: |
          go get -u honnef.co/go/tools/cmd/staticcheck
          staticcheck ./...

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get binary from build job
        uses: actions/download-artifact@v2
        with:
          name: binary

      - name: AWS CodeDeploy
        uses: sourcetoad/aws-codedeploy-action@v1
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          codedeploy_name: wheretogo
          codedeploy_group: prod
          directory: ./
          s3_bucket: codemonauts-codeship
          s3_folder: wheretogo
